stages:
- test
pytest:
stage: test
image: python:3.11
script:
- pip install -r requirements.txt
- python -m pytest --junitxml=junit.xml
artifacts:
reports:
junit: junit.xml
deployment:
stage: deploy
script:
- curl https://api.render.com/deploy/srv-d5vt6bfpm1nc73cstvjg?key=DfH1Uijzkrw
only:
- main